### ISSUE TITLE
some problem in demo_graph.py

### ISSUE THREAD

**Issue by JiYuanFeng** [endernewton/c2board#1]
Hi! 
the code in demo_graph.py 
`writer.add_graph()`
i think should be ？？
`writer.write_graph()`

I run my code without any problem, but I don't know how to enter the Tensorboard in browsers.

whatever, the c2board will  benefit so much to the caffe2 user

Thank you~

**Comment by endernewton** [comment]
Thanks! nice catch! fixed that.
